### ISSUE TITLE
ffprobe Error when running via systemd

### ISSUE THREAD

**Issue by insanity54** [insanity54/clipzip#1]
```
Apr 20 14:58:00 ti83plus node[44682]: downloading channel:bunny_gif
Apr 20 14:58:21 ti83plus node[44682]: Error: spawn ffprobe ENOENT
Apr 20 14:58:21 ti83plus node[44682]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
Apr 20 14:58:21 ti83plus node[44682]:     at onErrorNT (internal/child_process.js:465:16)
Apr 20 14:58:21 ti83plus node[44682]:     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Apr 20 14:58:21 ti83plus node[44682]:   errno: -2,
Apr 20 14:58:21 ti83plus node[44682]:   code: 'ENOENT',
Apr 20 14:58:21 ti83plus node[44682]:   syscall: 'spawn ffprobe',
Apr 20 14:58:21 ti83plus node[44682]:   path: 'ffprobe',
Apr 20 14:58:21 ti83plus node[44682]:   spawnargs: [
Apr 20 14:58:21 ti83plus node[44682]:     '-show_streams',
Apr 20 14:58:21 ti83plus node[44682]:     '-print_format',
Apr 20 14:58:21 ti83plus node[44682]:     'json',
Apr 20 14:58:21 ti83plus node[44682]:     '/home/chris/Documents/clipzip/data/bunny_gif/2021-02-01_2021-02-28/HungryAmazingLemurSMOrc-4nx4PGs5_WZ3Uzj9.mp4'
Apr 20 14:58:21 ti83plus node[44682]:   ]
Apr 20 14:58:21 ti83plus node[44682]: }
```

**Comment by insanity54** [comment]
I don't remember what the problem was, but it was fixed or worked around and it's not an issue anymore
